apiVersion: v1
kind: Pod
metadata:
  name: discordbot
  namespace: discordbot
  labels:
    purpose: demonstrate-discordbot
spec:  
  
  containers:
  - name: discordbot
    resources:
      requests:
        memory: "8Mi"
        cpu: "10m"
      limits:
        memory: "20Mi"
        cpu: "100m"
    image: aymon/hive.discordbot:v0.0.5
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: discordbottoken
          key: token

