apiVersion: v1
kind: Namespace
metadata:
  name: discordbot
  labels:
    name: discordbot
---
apiVersion: v1
kind: Pod
metadata:
  name: discordbot
  namespace: discordbot
  labels:
    purpose: demonstrate-discordbot
spec:  
  
  containers:
  - name: discordbot
    resources:
      requests:
        memory: "8Mi"
        cpu: "10m"
      limits:
        memory: "20Mi"
        cpu: "100m"
    image: aymon/hive.discordbot:v0.0.4
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: discordbottoken
          key: token
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    purpose: discordbot
data:
  commands.yaml: |
    ping: pong
    hello: Hi!
    version: v0.0.4
  version.yaml: |
    version: v0.0.4
    \n
