name: Workflow for Codecov, Go Report Action
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0
